export const products = [
    {
        id: 1,
        name: "Adrian Yellow Stitch Ambassador Leather Loafers",
        price: 135,
        image: ["/images/products/product-1(0).webp", "/images/products/product-1(1).webp", "/images/products/product-1(2).webp", "/images/products/product-1(3).webp", "/images/products/product-1(4).webp"],
        category: "SHOES",
        description: "We’ve gone soft. We’ve rebuilt our classic Adrian tassel loafer using luxurious Ambassador leather, a tumbled material with an oiled finish and a soft handle that makes slipping into an Original Dr. Martens silhouette even easier. The sole is secured with DM’s yellow welt stitching and marked with our signature grooving pattern.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 2,
        name: "8053 Arc Crazy Horse Leather Platform Casual Shoes",
        price: 148,
        image: ["/images/products/product-2(0).webp", "/images/products/product-2(1).webp", "/images/products/product-2(2).webp", "/images/products/product-2(3).webp", "/images/products/product-2(4).webp"],
        category: "SHOES",
        description: "Feel the Buzz. Inspired by our 90s silhouettes, the new Buzz 5-eye shoe grabs attention from top to bottom. It stands on our chunky barrel-edge Buzz sole — marked with DM’s grooving, yellow welt stitching, and a leaf pattern on the undersole. The soft Grizzly leather upper has a comfortable padded collar, contrast stitch detailing, and an inflated, rubberised badge that echoes the contours of the sole.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 3,
        name: "Zebzag",
        price: 148,
        image: ["/images/products/product-3(0).webp", "/images/products/product-3(1).webp", "/images/products/product-3(2).webp", "/images/products/product-3(3).webp", "/images/products/product-3(4).webp"],
        category: "SHOES",
        description: "The Zebzag mule is our latest innovation in comfort: built on a hybrid air-cushioned sole that fuses feather-weight EVA with rugged PVC. Crafted from lightweight, versatile suede, they’re designed to be worn however you feel like – in summer or out of the conventional season. The adjustable strap ensures a secure fit, while the welted construction delivers our signature durability. Yellow welt stitching marks the mules as Dr. Martens.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 4,
        name: "Brookline",
        price: 135,
        image: ["/images/products/product-3(0).webp", "/images/products/product-3(1).webp", "/images/products/product-3(2).webp", "/images/products/product-3(3).webp", "/images/products/product-3(4).webp"],
        category: "SHOES",
        description: "Go low-key. The newest addition to our Casual collection, the Brookline shoes offer hints of DM’s attitude in a minimalistic, fuss-free design. Its Brookline sole is lightweight and air-cushioned, built for comfort straight out of the box. The uppers feature a durable 10oz canvas construction and a 6-eye fastening with tonal laces.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 5,
        name: "Voss II",
        price: 135,
        image: ["/images/products/product-5(0).webp", "/images/products/product-5(1).webp", "/images/products/product-5(2).webp", "/images/products/product-5(3).webp", "/images/products/product-5(4).webp"],
        category: "SANDALS",
        description: "Keep summer easy. The Voss II sandal is lightweight and versatile for a summer on the move. The cross-strap design is secured with two adjustable ankle straps. Built for comfort on long days, it has a SoftWair memory foam footbed and our super-light EVA Zebrilus sole. The serrated sole is grooved and secured with our unmistakable yellow welt stitching.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 6,
        name: "Voss II",
        price: 135,
        image: ["/images/products/product-6(0).webp", "/images/products/product-6(1).webp", "/images/products/product-6(2).webp", "/images/products/product-6(3).webp", "/images/products/product-6(4).webp"],
        category: "SANDALS",
        description: "We've reinvented our headlining Gryphon sandal for the new season. Now standing on a high-rise Quad sole, the Gryphon Quad is manufactured from soft Pisa leather with rugged brass hardware. Welted, well-engineered and packed with Docs DNA — the sandals are finished with yellow welt stitching and an AirWair heel loop.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 7,
        name: "Kole",
        price: 135,
        image: ["/images/products/product-7(0).webp", "/images/products/product-7(1).webp", "/images/products/product-7(2).webp", "/images/products/product-7(3).webp", "/images/products/product-7(4).webp"],
        category: "SHOES",
        description: "Relax, it’s summer. Our new Kole sandal combines a pillow-soft padded upper with a super-lightweight sole — so you can take your home comforts for a spin on the street. The molded SoftWair footbed and EVA sole will feel like walking on air, while the adjustable Ripstop strap helps you find the perfect fit. Finished with signature DM’s yellow welt stitching.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 8,
        name: "Anistone Hi Leather Biker Boots",
        price: 135,
        image: ["/images/products/product-7(0).webp", "/images/products/product-7(1).webp", "/images/products/product-7(2).webp", "/images/products/product-7(3).webp", "/images/products/product-7(4).webp"],
        category: "BOOT",
        description: "Start your engines. Our new Anistone Hi biker boot is built from Wanama leather and fitted with industrial-inspired hardware including branded metal plates and an adjustable buckle. Set on our elevated Bex sole.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 9,
        name: "Combs",
        price: 135,
        image: ["/images/products/product-9(0).webp", "/images/products/product-9(1).webp", "/images/products/product-9(2).webp", "/images/products/product-9(3).webp", "/images/products/product-9(4).webp"],
        category: "BOOT",
        description: "Engineered to go. The Combs W 6-eye boot has everyday wear in its DNA. A combination of rugged Bronx Suede that takes on more character with wear. And Extra Tough 50/50 material. The boots as durable as it is lightweight. Hiker-inspired silver hardware and tonal laces line the upper. Our scripted heel loop and yellow faux welt stitching mark the boot as DMs. And we finished the silhouette with a black and smoke Tract sole.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 10,
        name: "Top Handle Bag",
        price: 135,
        image: ["/images/products/product-10(0).webp", "/images/products/product-10(1).webp", "/images/products/product-10(2).webp", "/images/products/product-10(3).webp", "/images/products/product-10(4).webp"],
        category: "ACCESSORIES",
        description: "All of the attitude of our weekender bag, built for your everyday. The bag features the same bold silhouette and versatile storage options, with a zippable spacious main compartment and two buckle-fastened external pockets. Two carry handles offer an easy grab-and-go design, and a removable crossbody shoulder strap adds a second wearing option. It’s finished with silver hardware and Dr. Martens accents that’ll be recognised anywhere.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
    {
        id: 11,
        name: "Ambassador Leather Reporter Bag",
        price: 135,
        image: ["/images/products/product-11(0).webp", "/images/products/product-11(1).webp", "/images/products/product-11(2).webp", "/images/products/product-11(3).webp", "/images/products/product-11(4).webp"],
        category: "ACCESSORIES",
        description: "The Reporter bag is a stylish and functional bag that is perfect for any occasion. It is made with high-quality leather and is designed to be comfortable and durable.",
        rating: 4.5,
        reviews: 100,
        isNew: true,
        isFeatured: true,
        isBestSeller: true,
        isSale: true,
    },
]

export const categories = [
  "SHOES",
  "SANDALS",
  "BOOT",
  "ACCESSORIES",
]